### PR TITLE
Release data 30/07/2021

### PR DESCRIPTION
**Pull request by Wkt8**
This PR contains the test data to accompany the schema changes in this PR (https://github.com/HumanCellAtlas/metadata-schema/pull/1388), with changes made for the ontology labels and estimated_cell_count. 

**Versions updated**:
- type/project/project.json: 14.3.0

**Issues addressed**:
- https://github.com/HumanCellAtlas/metadata-schema/issues/1343

### CODE REVIEW

**Review by hannes-ucsc — CHANGES_REQUESTED** [review]
This PR mixes in an unrelated change to the `library_construction_method` property of two library preparation protocols. It may seem pedantic but I want to set the precedent of one change - one PR. We don't want a PR per "release", we want a PR per logical schema change. Is that something your workflow supports? If not, at the very least, cleanly split up the commits. Currently, parts of the `library_construction_method` change are present in both commits.

**Comment by ESapenaVentura** [comment]
@hannes-ucsc done, the ontology change is in master so now the only changes shown in the PR are:
- Addition of estimated_cell_count field
- Bump of minor version

**Review by hannes-ucsc — APPROVED** [review]

**Review by kbergin — APPROVED** [review]

**Review by kbergin — APPROVED** [review]

**Review by ESapenaVentura — APPROVED** [review]

**Review by ruchim — APPROVED** [review]
Looks good to me!

**Review by NoopDog — APPROVED** [review]

**Review by aherbst-broad — APPROVED** [review]

**Comment by ESapenaVentura** [comment]
As stated in https://embl-ebi-ait.slack.com/archives/C01360XN04S/p1628773358050500?thread_ts=1628773291.050300&cid=C01360XN04S we will merge without @amnonkhen 's explicit approval, since he will be on holidays for 2 weeks but he already reviewed this PR internally

**Pull request merged**
